// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8b0QPx-z58QSQVoE5lD4VdTd2JMMoOpE',
    appId: '1:660117236741:web:ea308ee94c88220017c06c',
    messagingSenderId: '660117236741',
    projectId: 'chatapp2-1c226',
    authDomain: 'chatapp2-1c226.firebaseapp.com',
    storageBucket: 'chatapp2-1c226.firebasestorage.app',
    measurementId: 'G-1Q3ZP3MNYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQhkSEUaigxuFHiBfg4QIT0aAjhjTmyao',
    appId: '1:660117236741:android:feb57ed613e1689417c06c',
    messagingSenderId: '660117236741',
    projectId: 'chatapp2-1c226',
    storageBucket: 'chatapp2-1c226.firebasestorage.app',
  );
}
